language: ruby

services:
  - docker

before_install:
  - docker pull jasoet/cx-jvm:8

script:
  - docker run --rm -it -v $(pwd):/work -w /work/dist jasoet/cx-jvm:8 kscript --package ../src/main/kotlin/SimpleServerMock.kts